EWRAPPERS = [[['tickPrice'], ['TickerId tickerId', 'TickType field', 'double price', 'int canAutoExecute']],
             [['tickSize'], ['TickerId tickerId', 'TickType field', 'int size']], [['tickOptionComputation'],
                                                                                   ['TickerId tickerId',
                                                                                    'TickType tickType',
                                                                                    'double impliedVol', 'double delta',
                                                                                    'double optPrice',
                                                                                    'double pvDividend', 'double gamma',
                                                                                    'double vega', 'double theta',
                                                                                    'double undPrice']],
             [['tickGeneric'], ['TickerId tickerId', 'TickType tickType', 'double value']],
             [['tickString'], ['TickerId tickerId', 'TickType tickType', 'const IBString value']], [['tickEFP'], [
        'TickerId tickerId', 'TickType tickType', 'double basisPoints', 'const IBString formattedBasisPoints',
        'double totalDividends', 'int holdDays', 'const IBString futureExpiry', 'double dividendImpact',
        'double dividendsToExpiry']], [['orderStatus'],
                                       ['OrderId orderId', 'const IBString status', 'int filled', 'int remaining',
                                        'double avgFillPrice', 'int permId', 'int parentId', 'double lastFillPrice',
                                        'int clientId', 'const IBString whyHeld']],
             [['openOrder'], ['OrderId orderId', 'const Contract', 'const Order', 'const OrderState']],
             [['openOrderEnd'], ['']], [['winError'], ['const IBString str', 'int lastError']],
             [['connectionClosed'], ['']], [['updateAccountValue'],
                                            ['const IBString key', 'const IBString value', 'const IBString currency',
                                             'const IBString accountName']], [['updatePortfolio'],
                                                                              ['const Contract contract',
                                                                               'int position', 'double marketPrice',
                                                                               'double marketValue',
                                                                               'double averageCost',
                                                                               'double unrealizedPNL',
                                                                               'double realizedPNL',
                                                                               'const IBString accountName']],
             [['updateAccountTime'], ['const IBString timeStamp']],
             [['accountDownloadEnd'], ['const IBString accountName']], [['nextValidId'], ['OrderId orderId']],
             [['contractDetails'], ['int reqId', 'const ContractDetails contractDetails']],
             [['bondContractDetails'], ['int reqId', 'const ContractDetails contractDetails']],
             [['contractDetailsEnd'], ['int reqId']],
             [['execDetails'], ['int reqId', 'const Contract contract', 'const Execution execution']],
             [['execDetailsEnd'], ['int reqId']],
             [['error'], ['const int id', 'const int errorCode', 'const IBString errorMsg']], [['updateMktDepth'],
                                                                                               ['TickerId id',
                                                                                                'int position',
                                                                                                'int operation',
                                                                                                'int side',
                                                                                                'double price',
                                                                                                'int size']],
             [['updateMktDepthL2'],
              ['TickerId id', 'int position', 'IBString marketMaker', 'int operation', 'int side', 'double price',
               'int size']], [['updateNewsBulletin'],
                              ['int msgId', 'int msgType', 'const IBString newsMessage', 'const IBString originExch']],
             [['managedAccounts'], ['const IBString accountsList']],
             [['receiveFA'], ['faDataType pFaDataType', 'const IBString cxml']], [['historicalData'], ['TickerId reqId',
                                                                                                       'const IBString date',
                                                                                                       'double open',
                                                                                                       'double high',
                                                                                                       'double low',
                                                                                                       'double close',
                                                                                                       'int volume',
                                                                                                       'int barCount',
                                                                                                       'double WAP',
                                                                                                       'int hasGaps']],
             [['scannerParameters'], ['const IBString xml']], [['scannerData'], ['int reqId', 'int rank',
                                                                                 'const ContractDetails contractDetails',
                                                                                 'const IBString distance',
                                                                                 'const IBString benchmark',
                                                                                 'const IBString projection',
                                                                                 'const IBString legsStr']],
             [['scannerDataEnd'], ['int reqId']], [['realtimeBar'],
                                                   ['TickerId reqId', 'long time', 'double open', 'double high',
                                                    'double low', 'double close', 'long volume', 'double wap',
                                                    'int count']], [['currentTime'], ['long time']],
             [['fundamentalData'], ['TickerId reqId', 'const IBString data']],
             [['deltaNeutralValidation'], ['int reqId', 'const UnderComp underComp']],
             [['tickSnapshotEnd'], ['int reqId']], [['marketDataType'], ['TickerId reqId', 'int marketDataType']],
             [['commissionReport'], ['const CommissionReport commissionReport']],
             [['position'], ['const IBString account', 'const Contract contract', 'int position', 'double avgCost']],
             [['positionEnd'], ['']], [['accountSummary'], ['int reqId', 'const IBString account', 'const IBString tag',
                                                            'const IBString value', 'const IBString curency']],
             [['accountSummaryEnd'], ['int reqId']], [['verifyMessageAPI'], ['const IBString apiData']],
             [['verifyCompleted'], ['bool isSuccessful', 'const IBString errorText']],
             [['displayGroupList'], ['int reqId', 'const IBString groups']],
             [['displayGroupUpdated'], ['int reqId', 'const IBString contractInfo']]]
